# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod properties
mod_id=create_tweaked_controllers
mod_name=Create: Tweaked Controllers
mod_license=MIT
mod_version=1.21.1-1.3.0
mod_group_id=com.getitemfromblock.create_tweaked_controllers
mod_authors=getItemFromBlock
mod_description=A Create Addon that adds a way of controlling contraptions using an advanced controller. Compatible with Create 6.0.8+

# Minecraft/NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.77
neo_version_range=[21.1,)
loader_version_range=[4,)

# Parchment mappings
parchment_mc_version=1.21.1
parchment_version=2024.11.17

# Create ecosystem
create_version=6.0.8-169
create_version_range=[6.0.0,)
ponder_version=1.0.66
flywheel_version=1.0.5
registrate_version=MC1.21-1.3.0+62

# CC:Tweaked (optional compat)
cc_tweaked_version=1.117.0
